language: python
python:
  - "2.7"

before_install:
    - sudo apt-get remove -y libgdal1
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo rm -f /etc/apt/sources.list.d/pgdg-source.list
    - sudo apt-get update -qq
    - sudo apt-get install python-gdal
    - sudo apt-get install -y libgdal-dev libproj-dev gdal-bin binutils
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
    - sudo apt-get install postgresql-9.1
    - sudo apt-get install postgresql-9.1-postgis-2.1 
    - sudo apt-get install postgresql-9.1-postgis-scripts

# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database waymarkers;' -U postgres 
  - psql -U postgres -c "create extension postgis" -d waymarkers;

# command to run tests
script: ./manage.py test -v2
