language: python
python:
  - "2.7"

before_install:
    - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
    - sudo apt-get remove -y libgdal1
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update -y
    - sudo apt-get install -y gdal-bin
    - sudo apt-get install -y python-gdal
    
virtualenv:
  system_site_packages: true

# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database waymarkers;' -U gis 
  - psql -U postgres -c "create extension postgis"

# command to run tests
script: ./manage.py test
