nguage: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database waymarkers;' -U gis 
  - psql -U postgres -c "create extension postgis"

# command to run tests
script: ./manage.py test
